sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t spglab/wyk7 -f Dockerfile.dev2 .

script:
  - docker run -e CI=true spglab/wyk7 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "rogalskiawsapp"
  env: "rogalskiawsapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-983021526080"
  bucket_path: "rogalskiawsapp"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
